services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_URL: postgres://postgres:password@db:5432/github_monitor
      RAILS_ENV: development
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - ./log:/rails/log
      - ./tmp:/rails/tmp
      - ./storage:/rails/storage
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: github_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  bundle_cache:
